### ISSUE TITLE
Server not shown as online when home is assigned

### ISSUE THREAD

**Issue by Megamezzomixer** [OpenGamePanel/OGP-Website#348] opened 2018-05-31 11:59 UTC
When an account with a user role is assigned to a gameserver it won't show as online on the dashboard, even if it is.

Dashboard for my account (admin & server owner):
![2018-05-31_13-54-36](https://user-images.githubusercontent.com/21281507/40780984-8dbf9b3e-64da-11e8-8548-e81202d18198.png)

Dashboard for the user account (assigned to both servers):
![2018-05-31_13-57-15](https://user-images.githubusercontent.com/21281507/40781029-b4bb0778-64da-11e8-8a9a-d50c6270bdad.png)

An I doing something wrong?
The user can even control those servers in the "Game Monitor" tab.

**Comment by rocco27** [comment] 2018-05-31 12:11
Where did you assign this server for user?

**Comment by Megamezzomixer** [comment] 2018-05-31 12:28
I have assigned the user via Users -> Assign Homes. I also tried it over groups, it has the same problem.

**Comment by rocco27** [comment] 2018-05-31 12:29
W

**Comment by rocco27** [comment] 2018-05-31 12:29
Which version of Panel do you use?

**Comment by Megamezzomixer** [comment] 2018-05-31 12:31
The latest version: bda54c0b64707d5cbac3d9727528cf0faa53efca

**Comment by rocco27** [comment] 2018-05-31 19:39
I have same issue on my side.

**Comment by Megamezzomixer** [comment] 2018-05-31 21:21
Great to see that I'm not the only one with this problem. Might this be fixed? However, It's not a major issue.

**Comment by own3mall** [comment] 2018-06-01 22:50
I cannot reproduce this problem no matter how I try.  It always works for me when homes are assigned to groups or individual users.

Please describe exactly how to reproduce this problem step by step... as it stands right now, I can't reproduce, and I tried pretty hard...

**Comment by Megamezzomixer** [comment] 2018-06-02 08:46
I have created a new user with the user role. Then I just assigned that user to one or more servers via the Assign Homes function in the user list. Then I just logged into the new user and the bug appeared.

**Comment by own3mall** [comment] 2018-06-02 17:30
Yep, that doesn't happen for me.  It works fine.

**Comment by Megamezzomixer** [comment] 2018-06-02 17:36
I could make a video on it, but.. I don't see if it would help you.

**Comment by own3mall** [comment] 2018-06-02 20:54
Yes please do as there are several ways to assign home servers and create users.  The methods I tried didn't reproduce this issue.

**Comment by Megamezzomixer** [comment] 2018-06-03 10:28
Sadly I couldn't archieve better quality, but here is what I have done: https://youtu.be/E5AC_jqUGXs

**Comment by own3mall** [comment] 2018-06-04 14:55
Thanks for the video.  No matter what I tried, I was unable to reproduce the issue shown in your video.  

Here is something you could try:

Go to "Administration" --> "Panel Settings" -->change "Old Dashboard behavior" to "On" or "Off" depending on what you have set.

Then, if you want to troubleshoot what's going on, open "modules/dashboard/dashboard.php" and under line 65 which is the below line:

```
$server_homes = $db->getIpPortsForUser_limit($_SESSION['user_id'],$page_user,$limit_user);
```

Add a new line below the above line:
```
echo "<p>Server Homes Are:<br><br>" . print_r($server_homes, true) . "</p><p>Page user is " . $page_user . " and limit user is " . $limit_user . "</p>"; 
```

Send me the output that the page now generates.

**Comment by own3mall** [comment] 2018-06-04 15:07
And then, depending on your results, you may want to troubleshoot the getIpPortsForUser_limit function in includes/database_mysqli.php.

Play around with the generated SQL to see what might be going on.

**Comment by OnlyHardOfficial** [comment] 2018-06-04 19:59
Nice Guys!  :)

**Comment by Megamezzomixer** [comment] 2018-06-05 09:06
To your first approach: I switched the panel to the old behavior, didn't work.
And all your line puts out is the following:
``
Server Homes Are:

Page user is 1 and limit user is 25

**Comment by own3mall** [comment] 2018-06-05 14:04
Yep, so the SQL query shows no server homes have been assigned to the user.  As to why that is?  You'll need to debug the SQL the panel generates and play around with that SQL in PHPMyAdmin to figure out why...

That, or I suppose you could attach a backup of your ogp database for me to sift through.

**Comment by Megamezzomixer** [comment] 2018-06-05 14:17
Since I am not very experienced when it comes to databases and SQL queries, I'll just attach you an sql dump.
[ogp.zip](https://github.com/OpenGamePanel/OGP-Website/files/2072705/ogp.zip)

**Comment by own3mall** [comment] 2018-06-05 15:20
You can delete it.  I have it now.

**Comment by own3mall** [comment] 2018-06-05 15:23
Well how interesting... your database dump works for me.  The code returns what it should...

What OS and version are you running? MySQL / MariaDB version?

**Comment by Megamezzomixer** [comment] 2018-06-05 15:27
I am using Ubuntu 17.10 with MySQL 14.14 installed.

**Comment by Megamezzomixer** [comment] 2018-06-05 15:32
You expect a communication failure between server and agent?

**Comment by own3mall** [comment] 2018-06-05 16:08
I suspect a problem with the SQL query in newer MySQL or MariaDB installations...

I am going to test this on Ubuntu 18.04 - including the easy installer :+1:

**Comment by Megamezzomixer** [comment] 2018-06-05 16:10
Sounds reasonable. Hit me up if you find something.

**Comment by own3mall** [comment] 2018-06-05 17:05
Ok, it does appear to be a bug in newer versions of MySQL.  Once I add the order by clause, the result set is empty:

Working:

```
SELECT ogp_remote_server_ips.*,ogp_home_ip_ports.*,ogp_server_homes.*, ogp_remote_servers.*, ogp_config_homes.*, ogp_config_mods.*, ogp_game_mods.* FROM `ogp_home_ip_ports` NATURAL JOIN `ogp_remote_servers` NATURAL JOIN `ogp_server_homes` NATURAL JOIN `ogp_config_homes` NATURAL JOIN `ogp_remote_server_ips` NATURAL JOIN `ogp_config_mods` NATURAL JOIN `ogp_game_mods` WHERE `home_id` IN ( SELECT `home_id` FROM `ogp_user_homes` WHERE `user_id` = 4 UNION SELECT `home_id` FROM `ogp_user_groups` NATURAL JOIN `ogp_user_group_homes` WHERE `user_id` = 4 ) AND `force_mod_id` IN ( SELECT `force_mod_id` FROM `ogp_home_ip_ports` WHERE `force_mod_id` = ogp_game_mods.mod_id OR `force_mod_id` = "0" )
```

Broken

```
SELECT ogp_remote_server_ips.*,ogp_home_ip_ports.*,ogp_server_homes.*, ogp_remote_servers.*, ogp_config_homes.*, ogp_config_mods.*, ogp_game_mods.* FROM `ogp_home_ip_ports` NATURAL JOIN `ogp_remote_servers` NATURAL JOIN `ogp_server_homes` NATURAL JOIN `ogp_config_homes` NATURAL JOIN `ogp_remote_server_ips` NATURAL JOIN `ogp_config_mods` NATURAL JOIN `ogp_game_mods` WHERE `home_id` IN ( SELECT `home_id` FROM `ogp_user_homes` WHERE `user_id` = 4 UNION SELECT `home_id` FROM `ogp_user_groups` NATURAL JOIN `ogp_user_group_homes` WHERE `user_id` = 4 ) AND `force_mod_id` IN ( SELECT `force_mod_id` FROM `ogp_home_ip_ports` WHERE `force_mod_id` = ogp_game_mods.mod_id OR `force_mod_id` = "0" ) **ORDER BY ogp_home_ip_ports.home_id ASC**
```

Suggested fix:

```
**SELECT * FROM** `ogp_home_ip_ports` NATURAL JOIN `ogp_remote_servers` NATURAL JOIN `ogp_server_homes` NATURAL JOIN `ogp_config_homes` NATURAL JOIN `ogp_remote_server_ips` NATURAL JOIN `ogp_config_mods` NATURAL JOIN `ogp_game_mods` WHERE `home_id` IN ( SELECT `home_id` FROM `ogp_user_homes` WHERE `user_id` = 4 UNION SELECT `home_id` FROM `ogp_user_groups` NATURAL JOIN `ogp_user_group_homes` WHERE `user_id` = 4 ) AND `force_mod_id` IN ( SELECT `force_mod_id` FROM `ogp_home_ip_ports` WHERE `force_mod_id` = ogp_game_mods.mod_id OR `force_mod_id` = "0" ) ORDER BY ogp_home_ip_ports.home_id ASC
```

**Comment by Megamezzomixer** [comment] 2018-06-05 17:13
Will this be in an official update?

OwN-3m-All <notifications@github.com> schrieb am Di., 5. Juni 2018, 19:05:

**Comment by own3mall** [comment] 2018-06-05 18:12
Nope, a better solution was found:

https://github.com/own3mall/OGP-Website/commit/a1bbc7db154eb8081e8277c46f1eaa1efdba896b

Why does that work and the old query doesn't?  I have no idea... our queries can be rather complex...

Anyways, update your panel and let me know if it's fixed.

**Comment by Megamezzomixer** [comment] 2018-06-05 18:24
It works. Online servers are now properly displayed.

**Comment by own3mall** [comment] 2018-06-05 18:32
Great, we may need to do this in other sections, so if you notice any other strange behavior, please let us know.  Thanks for reporting!

**Comment by Megamezzomixer** [comment] 2018-06-05 18:34
Yea, will do. Thanks for fixing to so fast!

**Comment by rocco27** [comment] 2018-06-05 19:08
It works now on my side! Thank you guys! <3

**Comment by own3mall** [comment] 2018-06-05 21:02
https://github.com/OpenGamePanel/OGP-Website/commit/0e6b4fa004162c438a13e296ef1056fd31f5ec78

I find this issue very strange... the behavior of different versions of MySQL makes no sense.  This appears to be better now anyways.

Seems legit:  https://makandracards.com/makandra/2681-mysql-do-not-use-where-id-in-select

**Comment by own3mall** [comment] 2018-06-05 21:05
@Megamezzomixer I would recommend changing your agent password just in case anyone else grabbed that SQL backup you provided.

**Comment by Megamezzomixer** [comment] 2018-06-05 21:07
Yeah! I was worried about my RCON passwords, but forgot the agent key...

**Comment by Megamezzomixer** [comment] 2018-06-05 21:12
Yeah, thanks for the warning. Apparently just as we spoke someone tried out the old RCON password on my Garry's Mod server :P

**Closed** 2018-06-05 21:17 UTC
Labels: Code Fix Implemented, SQL Issue
