### ISSUE TITLE
Problem in Administration/Game Servers

### ISSUE THREAD

**Issue by rocco27** [OpenGamePanel/OGP-Website#202] opened 2017-08-20 21:52 UTC
I have a Master server and it is assigned to the admin account. It doesn't have any port, because it doesn't need that. I go to 'Administration/Game Servers' and it is listing all game servers except the Master server which has no port.
If I add a port to the Master server, then it will be visible in 'Administration/Game Servers'.

I think it should be visible always - with and without port too in this sub-menu.

**Comment by Zorrototo** [comment] 2017-08-21 12:04
It was visible from Administration->Game Servers before (I remember creating servers and forgot to assign a port and found the server here because it was not in Game Monitor, if I'm not wrong) so it should be. Is it an update that changed that (with the new config field in the Agent server settings)? Or is it me who remember wrong?

But I agree that wether it has a port and/or IP assigned to it or not, it should always be visible for the Admin account in Administration->Game Server and also in Game Monitor. It will avoid any problem like we have seen recently on the forum with 'ghost servers'.

**Comment by Adjokip** [comment] 2017-08-21 12:07
This will happen regardless of it being a master server or not.

It's the same issue as what was posted [here](http://www.opengamepanel.org/forum/viewthread.php?thread_id=5609#post_28609) - create a server, don't assign a port, and it's not visible any where in the panel.

It's been present since @Obada8 added the pagination/search function (https://github.com/OpenGamePanel/OGP-Website/commit/c355793fb7f650c8105e6de76d80edce338fdb2d)

I'll look into it soon if no one else can.

**Comment by Obada8** [comment] 2017-08-21 15:05
I'm sorry for that issue, i didn't be attention on this....
These days i'm busy with my work, but i'll take a look when i go to my home and send the result here.
Sorry again.

**Comment by Obada8** [comment] 2017-08-22 10:47
@Adjokip Do you have any idea if we remove those `NATURAL JOIN %1$shome_ip_ports NATURAL JOIN %1$sremote_server_ips` From those lines [L2698 ](https://github.com/OpenGamePanel/OGP-Website/blob/master/includes/database_mysql.php#L2698)& [L2705](https://github.com/OpenGamePanel/OGP-Website/blob/master/includes/database_mysqli.php#L2705)

**Comment by rocco27** [comment] 2017-08-22 12:51
@Zorrototo yes it worked before.
@Obada8 No problem, sometimes shit happens, but we are here to catch the bugs and fix those. Fortunatelly it is not a dangerius one. 😁

**Comment by own3mall** [comment] 2017-08-23 02:01
@Adjokip what was the gist of the problem you fixed?  What was the root cause, and how specifically was the query changed to fix it?  I don't like looking through those queries to begin with :)

**Comment by own3mall** [comment] 2017-08-23 02:10
nvm, you explained it here:  https://github.com/OpenGamePanel/OGP-Website/pull/206

Should be fixed now thanks to @Adjokip

**Closed by own3mall** 2017-08-23 02:10 UTC
