### ISSUE TITLE
New search fields problems

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/OGP-Website#180] opened 2017-07-06 03:15 UTC
Two connected issues: 

When you are in Admin User list, and you search for a partial name (let say I have a user "Vodka" and I search for "Vodk"), it does not return any result. I tried also the 'joker' character but no luck. Partial searches are not supported.

When you are in Admin Game Servers list, I simply can't find a way to have a result (OK with empty search field it returns the whole game servers list, or if you put the IP too it returns the whole list if you have one IP only, or if you put the server ID it also works), whatever I try (part of server name, .....) I can't have any result, it always returns 'No game servers found' (by the way this message is not displayed as a 'failure' thing in red but as standard text).

Problem here is that partial searches simply do not work you need to have exactly the right thing written or it fails.

It is the same for the other search fields elsewhere. partial searches do not work

While testing I found that bug too: in game monitor, if you search for example one word from the server title, the page returns this error, which is obviously unrelated to the search: `No game servers assigned for you. You need to ask your OGP admin to assign games for you.` I am an Admin on my Panel and have all servers visible at Game Monitor.

**Comment by Obada8** [comment] 2017-07-07 15:48
I need to add another issue here, when i search for server with another owner username the search not showing the results. For example: my username is Administrator [Admin role] and i owned all game server else home_id = 84 [Owner name is test] when i search for this home_id via type ip for this home_id the search result show all game server which have this ip, but not show this home which had same ip.

**Comment by own3mall** [comment] 2017-07-08 19:24
@Obada8 Please be more specific.  How do I reproduce your page number problem step by step?  I don't understand what you're saying.

**Comment by Obada8** [comment] 2017-07-09 00:57
@own3mall I'm very sorry for my bad english :\ .
I mean try to make game server like [screenshot](https://s17.postimg.org/wbngr03cv/chrome_2017-07-08_03-39-15.png).
And go to list all game servers and search via ip only.

**Comment by own3mall** [comment] 2017-07-09 17:29
I believe all you would have to do is update the paging links to include the search field input as part of the URL if there is any?  Then it would work?

**Comment by Obada8** [comment] 2017-07-09 18:04
Yes, but this is wrong because displaying the page number in the link should return to the search results and not to the display of the game server (before click search).

**Comment by own3mall** [comment] 2017-07-09 22:13
@Obada8 I still don't understand what your problem is.  Is it still broken in the latest version of the OGP panel?  Update your panel to test.

**Comment by Obada8** [comment] 2017-07-09 22:17
@own3mall  I use latest update yes (just leave GitHub field empty in panel setting then click update)
anyway does search function work with you? even if game server not showing in first page?

**Comment by Adjokip** [comment] 2017-07-09 23:01
The commit from last night (#183) appears to have a typo in the query. `$search_fields` instead of `$search_field`

Changing `$search_fields` to `$search_field` should fix it.

**Comment by own3mall** [comment] 2017-07-10 04:58
@Adjokip good catch.  That should be fixed now.

**Comment by own3mall** [comment] 2017-07-10 04:58
@Obada8 Please try it now.

**Comment by Obada8** [comment] 2017-07-10 11:19
Yes everything is working, @Adjokip  you have eagle eye :D

**Closed** 2017-07-26 01:36 UTC
